### ISSUE TITLE
Issue when serial number is not a number

### ISSUE THREAD

**Issue by jpulik** [piotrbulinski/flexit_bacnet#25]
Hi!,
I was prompted to update my Flexit Nordic S3 by Flexit GO app so I did so. After udating serial number of my unit was changed to `Nordic` and all settings were reset to factory defaults for some unknown reason (maybe some Flexit bug).
The problem I have now is I'm unable to use this integration as I get following error when setting it up:
```
Error while setting up flexit_bacnet platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/usr/src/homeassistant/homeassistant/components/flexit_bacnet/climate.py", line 47, in async_setup_entry
    async_add_entities([FlexitClimateEntity(coordinator)])
                        ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/flexit_bacnet/climate.py", line 80, in __init__
    super().__init__(coordinator)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/flexit_bacnet/entity.py", line 29, in __init__
    model_id=coordinator.device.model,
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/flexit_bacnet/device.py", line 74, in model
    model = NORDIC_MODELS.get(int(self.serial_number[0:6]))
                              ~~~^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Nordic'
```

Sadly I'm unable to change the serial number by myself. Can this be please fixed somehow in this integration so it won't crash anymore? Can we maybe treat serial number as a String instead of Int?

Thank you!

**Comment by piotrbulinski** [comment]
I’ll look into it some time next week.

**Comment by piotrbulinski** [comment]
@jpulik when you go in the Flexit Go app to the "More > System info" section, what's the serial number for your unit?  Is it something like "Nordic 800220-000000"?

**Comment by jpulik** [comment]
@piotrbulinski it just says "Nordic". Nothing more. I can provide screenshot if you want.

**Comment by piotrbulinski** [comment]
@jpulik thank you. I’ll work on the fix this week.

**Comment by piotrbulinski** [comment]
I've released a new version in PyPI which has the fix in it: https://pypi.org/project/flexit-bacnet/2.2.2/

**Comment by jpulik** [comment]
Thank you very much! Will it be automatically included in a next HA release or do I need to perform any additional actions?

**Comment by piotrbulinski** [comment]
@jpulik it has been merged into home assistant, so most likely will be part of the next release.

**Comment by jpulik** [comment]
@piotrbulinski 
Sadly, I updated to HA v. 2025.3.4 and it seems the issue is still there.
From the logs it seems like the previous point of failure was fixed but there is new one in `device.py` on line 74.
See the log:
```
2025-03-29 07:47:24.070 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up flexit_bacnet platform for binary_sensor: invalid literal for int() with base 10: 'Nordic'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 390, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 681, in async_add_entities
    for entity in new_entities:
                  ^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/flexit_bacnet/binary_sensor.py", line 46, in <genexpr>
    FlexitBinarySensor(coordinator, description) for description in SENSOR_TYPES
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/flexit_bacnet/binary_sensor.py", line 65, in __init__
    super().__init__(coordinator)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/flexit_bacnet/entity.py", line 29, in __init__
    model_id=coordinator.device.model,
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/flexit_bacnet/device.py", line 74, in model
    model = NORDIC_MODELS.get(int(self.serial_number[0:6]))
                              ~~~^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Nordic'
```

**Comment by jpulik** [comment]
@piotrbulinski I'm sorry for this but for some reason it seems like this library is still not updated to fixed version (2.2.2 or higher) in HA. 
I was waiting several releases and I also tried clean installation of HAOS recently but nothing helped. 
Based on the error in logs it seems like the change you made is not reflected in HA for some reason. **Notice the line 74 is the old one (but it is the latest HA (core) version - 2025.8.3)**.
There is still this line:
```
File "/usr/local/lib/python3.13/site-packages/flexit_bacnet/device.py", line 74, in model
    model = NORDIC_MODELS.get(int(self.serial_number[0:6]))
                              ~~~^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Nordic'
```
I tried searching but I'm lost about how to check what version of library does HA use. 
Can you somehow please help me / guide me what can I do here?
Thank you!

**Comment by piotrbulinski** [comment]
@jpulik the change has made it into `dev` and `master` branch in February: https://github.com/home-assistant/core/blob/dev/homeassistant/components/flexit_bacnet/manifest.json so I would expect it to be already released. Perhaps the [Home Assistant community forum](https://community.home-assistant.io/categories) would be a better place to debug this issue?

**Comment by jpulik** [comment]
Ok, for anyone who want to follow this discussion, I created topic in HA community forum here:
[https://community.home-assistant.io/t/how-to-ensure-integration-was-updated-in-core/924967](url)
